#!/usr/bin/env python3
"""Generate a Gazebo Classic .world (and model.config) from a world manifest.

    scripts/build_world.py turtlebot3_world
    scripts/build_world.py --all
    scripts/build_world.py /path/to/my_office     # a world outside the registry

Reads <world>/world.yaml and writes <world>/<name>.world plus
<world>/model.config. Both are committed: they are text, they are reviewable in
a diff, and committing them means the Gazebo backend needs no build step before
`ros2 launch`.

The Isaac Sim side is generated from the SAME manifest by
scripts/build_world_usd.py, which is the entire point of the layout — the two
simulators cannot drift because neither is hand-authored. scripts/build_world.sh
runs both.

Every generated file carries the manifest's sha256 in its header, so a
hand-edit of a generated file, or a manifest edited without regenerating, is a
one-line diff rather than a silent divergence. scripts/check_worlds.py checks it.

Mesh URIs are emitted as `model://<name>/meshes/...` rather than absolute paths,
so the generated file stays portable. That resolves only because worlds/ is on
GAZEBO_MODEL_PATH and each world directory carries a model.config, which is what
makes Gazebo's model database pick it up; both are wired in docker-compose.yml.

Pure stdlib + PyYAML, so this runs on the host or inside tb3_ros without ROS.
"""

import argparse
import hashlib
import os
import sys

sys.path.insert(0, os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))), 'tb3_bringup'))

from tb3_bringup import worlds  # noqa: E402

# No double hyphen anywhere in here: this text goes inside an XML comment, and
# `--` is illegal there. XML parsers reject the file outright rather than
# warning, so the generated world would fail to load for a purely cosmetic
# reason.
#
# The digest is what makes this more than a request. scripts/check_worlds.py
# recomputes it from world.yaml; a mismatch means either this file was edited
# by hand or the manifest moved on without a regenerate, and both are the
# beginning of the two backends describing different rooms.
GENERATED_BANNER = (
    'GENERATED by scripts/build_world.py from world.yaml. DO NOT EDIT.\n'
    '       Edit {name}/world.yaml and regenerate: scripts/build_world.sh {name}\n'
    '       {stamp}'
)

#: The provenance line, and the prefix check_worlds.py greps for.
STAMP = 'world.yaml sha256: {digest}'


def digest(manifest_path):
    with open(manifest_path, 'rb') as f:
        return hashlib.sha256(f.read()).hexdigest()


def banner(name, manifest_path):
    return GENERATED_BANNER.format(
        name=name, stamp=STAMP.format(digest=digest(manifest_path)))

# Upstream turtlebot3_world.world's solver settings, kept verbatim so that a
# world generated here steps identically to the stock one. Nav2 tuning is
# sensitive to contact behaviour, and silently changing the solver would make
# any sim-to-sim comparison meaningless.
PHYSICS = """    <physics type="ode">
      <real_time_update_rate>1000.0</real_time_update_rate>
      <max_step_size>0.001</max_step_size>
      <real_time_factor>1</real_time_factor>
      <ode>
        <solver>
          <type>quick</type>
          <iters>150</iters>
          <precon_iters>0</precon_iters>
          <sor>1.400000</sor>
          <use_dynamic_moi_rescaling>1</use_dynamic_moi_rescaling>
        </solver>
        <constraints>
          <cfm>0.00001</cfm>
          <erp>0.2</erp>
          <contact_max_correcting_vel>2000.000000</contact_max_correcting_vel>
          <contact_surface_layer>0.01000</contact_surface_layer>
        </constraints>
      </ode>
    </physics>"""


def pose_str(body):
    xyz = body.get('xyz', [0, 0, 0])
    rpy = body.get('rpy', [0, 0, 0])
    return ' '.join(f'{v:g}' for v in list(xyz) + list(rpy))


def geometry_xml(world_name, geom, indent):
    pad = ' ' * indent
    t = geom['type']
    if t == 'cylinder':
        return (f'{pad}<cylinder>\n'
                f'{pad}  <radius>{geom["radius"]:g}</radius>\n'
                f'{pad}  <length>{geom["length"]:g}</length>\n'
                f'{pad}</cylinder>')
    if t == 'box':
        sx, sy, sz = geom['size']
        return f'{pad}<box>\n{pad}  <size>{sx:g} {sy:g} {sz:g}</size>\n{pad}</box>'
    if t == 'sphere':
        return f'{pad}<sphere>\n{pad}  <radius>{geom["radius"]:g}</radius>\n{pad}</sphere>'
    if t == 'mesh':
        scale = geom.get('scale', [1.0, 1.0, 1.0])
        return (f'{pad}<mesh>\n'
                f'{pad}  <uri>model://{world_name}/{geom["uri"]}</uri>\n'
                f'{pad}  <scale>{" ".join(f"{v:g}" for v in scale)}</scale>\n'
                f'{pad}</mesh>')
    raise SystemExit(f'build_world: unsupported geometry type {t!r}')


def build_world(manifest, head):
    name = manifest['name']
    parts = [
        '<?xml version="1.0"?>',
        f'<!-- {head} -->',
        '<sdf version="1.6">',
        '  <world name="default">',
        '    <include><uri>model://ground_plane</uri></include>',
        '    <include><uri>model://sun</uri></include>',
        '    <scene><shadows>false</shadows></scene>',
        PHYSICS,
    ]

    bodies = manifest.get('bodies') or []
    if bodies:
        parts += [
            f'    <model name="{name}">',
            # Static: no rigid body, no inertia, nothing to integrate. The
            # manifest documents this as a whole-world property; a manifest that
            # ever needs movable props will need per-body <static> instead.
            '      <static>1</static>',
            '      <link name="symbol">',
        ]

    for body in bodies:
        bname, pose = body['name'], pose_str(body)
        geom = geometry_xml(name, body['geometry'], 12)
        parts += [
            f'        <collision name="{bname}">',
            f'          <pose>{pose}</pose>',
            '          <geometry>',
            geom,
            '          </geometry>',
            '        </collision>',
            f'        <visual name="{bname}">',
            f'          <pose>{pose}</pose>',
            '          <geometry>',
            geom,
            '          </geometry>',
            *material_xml(body),
            '        </visual>',
        ]

    if bodies:
        parts += ['      </link>', '    </model>']
    parts += ['  </world>', '</sdf>', '']
    return '\n'.join(parts)


def material_xml(body, indent=10):
    """A body's <material>, as numbers rather than an Ogre script name.

    SDF's own colour elements, not <script>, because the script name is a
    Gazebo-only token: Isaac Sim cannot resolve `Gazebo/White` and rendered
    every stage grey for as long as that was the only thing the manifest said
    about colour. worlds.material() resolves the stock names to the RGB in
    Gazebo's own gazebo.material, so a manifest written either way looks the
    same in both simulators.

    An empty list means "no <material> element at all" — the mesh brought its
    own, and Gazebo should use the .mtl beside it.
    """
    mat = worlds.material(body)
    if mat is None:
        return []
    pad = ' ' * indent
    r, g, b = mat['color']
    # Upstream's stock scripts set ambient == diffuse, so match them rather than
    # inventing an ambient term. Specular is derived from roughness so the field
    # is not inert on this backend; Gazebo Classic has no PBR, so this is the
    # closest honest mapping, and metallic has no analogue at all.
    spec = round((1.0 - mat['roughness']) * 0.5, 4)
    return [
        f'{pad}<material>',
        f'{pad}  <ambient>{r} {g} {b} 1</ambient>',
        f'{pad}  <diffuse>{r} {g} {b} 1</diffuse>',
        f'{pad}  <specular>{spec} {spec} {spec} 1</specular>',
        f'{pad}</material>',
    ]


def build_model_config(manifest, head):
    name = manifest['name']
    desc = ' '.join(manifest.get('description', '').split())
    return (
        '<?xml version="1.0"?>\n'
        f'<!-- {head} -->\n'
        '<model>\n'
        f'  <name>{name}</name>\n'
        '  <version>1.0</version>\n'
        f'  <sdf version="1.6">{name}.world</sdf>\n'
        f'  <description>{desc}</description>\n'
        '</model>\n'
    )


def generate(name_or_path):
    try:
        world = worlds.World.load(name_or_path)
    except RuntimeError as e:
        raise SystemExit(f'build_world: {e}')

    spec = world.artifact('gazebo')
    name, d = world.name, world.dir
    if spec['mode'] != 'generated':
        print(f'{name}: artifacts.gazebo.mode={spec["mode"]}, nothing to generate')
        return

    head = banner(name, os.path.join(d, worlds.MANIFEST))
    world_path = os.path.join(d, spec['path'])
    with open(world_path, 'w') as f:
        f.write(build_world(world.manifest, head))
    with open(os.path.join(d, 'model.config'), 'w') as f:
        f.write(build_model_config(world.manifest, head))

    n_mesh = sum(1 for b in world.bodies if b['geometry']['type'] == 'mesh')
    print(f'{name}: {len(world.bodies)} bodies ({n_mesh} mesh) -> {world_path}')


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument('world', nargs='?',
                    help='world name from the registry, or a path to a world '
                         'directory')
    ap.add_argument('--all', action='store_true', help='regenerate every world')
    ap.add_argument('--list', action='store_true', help='list available worlds')
    args = ap.parse_args()

    known = worlds.available()
    if args.list:
        print('\n'.join(known) if known else '(none)')
        return 0
    if args.all:
        for n in known:
            generate(n)
        return 0
    if not args.world:
        ap.error(f'name a world, or --all. Available: {", ".join(known) or "(none)"}')
    generate(args.world)
    return 0


if __name__ == '__main__':
    sys.exit(main())
