#!/usr/bin/env python3
"""Generate a Gazebo Classic .world (and model.config) from a world manifest.

    scripts/build_world.py turtlebot3_world
    scripts/build_world.py --all

Reads worlds/<name>/world.yaml and writes worlds/<name>/<name>.world plus
worlds/<name>/model.config. Both are committed: they are text, they are
reviewable in a diff, and committing them means the Gazebo backend needs no
build step before `ros2 launch`.

The Isaac Sim side is generated from the SAME manifest by
isaac/scripts/build_world_usd.py, which is the entire point of the layout — the
two simulators cannot drift because neither is hand-authored.

Mesh URIs are emitted as `model://<name>/meshes/...` rather than absolute paths,
so the generated file stays portable. That resolves only because worlds/ is on
GAZEBO_MODEL_PATH and each world directory carries a model.config, which is what
makes Gazebo's model database pick it up; both are wired in docker-compose.yml.

Pure stdlib + PyYAML, so this runs on the host or inside tb3_ros without ROS.
"""

import argparse
import os
import sys

import yaml

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
WORLDS = os.path.join(REPO, 'worlds')

# No double hyphen anywhere in here: this text goes inside an XML comment, and
# `--` is illegal there. XML parsers reject the file outright rather than
# warning, so the generated world would fail to load for a purely cosmetic
# reason.
GENERATED_BANNER = (
    'GENERATED by scripts/build_world.py from world.yaml. DO NOT EDIT.\n'
    '       Edit worlds/{name}/world.yaml and regenerate.'
)

# Upstream turtlebot3_world.world's solver settings, kept verbatim so that a
# world generated here steps identically to the stock one. Nav2 tuning is
# sensitive to contact behaviour, and silently changing the solver would make
# any sim-to-sim comparison meaningless.
PHYSICS = """    <physics type="ode">
      <real_time_update_rate>1000.0</real_time_update_rate>
      <max_step_size>0.001</max_step_size>
      <real_time_factor>1</real_time_factor>
      <ode>
        <solver>
          <type>quick</type>
          <iters>150</iters>
          <precon_iters>0</precon_iters>
          <sor>1.400000</sor>
          <use_dynamic_moi_rescaling>1</use_dynamic_moi_rescaling>
        </solver>
        <constraints>
          <cfm>0.00001</cfm>
          <erp>0.2</erp>
          <contact_max_correcting_vel>2000.000000</contact_max_correcting_vel>
          <contact_surface_layer>0.01000</contact_surface_layer>
        </constraints>
      </ode>
    </physics>"""


def pose_str(body):
    xyz = body.get('xyz', [0, 0, 0])
    rpy = body.get('rpy', [0, 0, 0])
    return ' '.join(f'{v:g}' for v in list(xyz) + list(rpy))


def geometry_xml(world_name, geom, indent):
    pad = ' ' * indent
    t = geom['type']
    if t == 'cylinder':
        return (f'{pad}<cylinder>\n'
                f'{pad}  <radius>{geom["radius"]:g}</radius>\n'
                f'{pad}  <length>{geom["length"]:g}</length>\n'
                f'{pad}</cylinder>')
    if t == 'box':
        sx, sy, sz = geom['size']
        return f'{pad}<box>\n{pad}  <size>{sx:g} {sy:g} {sz:g}</size>\n{pad}</box>'
    if t == 'sphere':
        return f'{pad}<sphere>\n{pad}  <radius>{geom["radius"]:g}</radius>\n{pad}</sphere>'
    if t == 'mesh':
        scale = geom.get('scale', [1.0, 1.0, 1.0])
        return (f'{pad}<mesh>\n'
                f'{pad}  <uri>model://{world_name}/{geom["uri"]}</uri>\n'
                f'{pad}  <scale>{" ".join(f"{v:g}" for v in scale)}</scale>\n'
                f'{pad}</mesh>')
    raise SystemExit(f'build_world: unsupported geometry type {t!r}')


def build_world(manifest):
    name = manifest['name']
    parts = [
        '<?xml version="1.0"?>',
        f'<!-- {GENERATED_BANNER.format(name=name)} -->',
        '<sdf version="1.6">',
        '  <world name="default">',
        '    <include><uri>model://ground_plane</uri></include>',
        '    <include><uri>model://sun</uri></include>',
        '    <scene><shadows>false</shadows></scene>',
        PHYSICS,
        f'    <model name="{name}">',
        # Static: no rigid body, no inertia, nothing to integrate. The manifest
        # documents this as a whole-world property; a manifest that ever needs
        # movable props will need per-body <static> instead.
        '      <static>1</static>',
        '      <link name="symbol">',
    ]

    for body in manifest['bodies']:
        bname, pose = body['name'], pose_str(body)
        geom = geometry_xml(name, body['geometry'], 12)
        parts += [
            f'        <collision name="{bname}">',
            f'          <pose>{pose}</pose>',
            '          <geometry>',
            geom,
            '          </geometry>',
            '        </collision>',
            f'        <visual name="{bname}">',
            f'          <pose>{pose}</pose>',
            '          <geometry>',
            geom,
            '          </geometry>',
            '          <material>',
            '            <script>',
            '              <uri>file://media/materials/scripts/gazebo.material</uri>',
            f'              <name>{body.get("material", "Gazebo/White")}</name>',
            '            </script>',
            '          </material>',
            '        </visual>',
        ]

    parts += ['      </link>', '    </model>', '  </world>', '</sdf>', '']
    return '\n'.join(parts)


def build_model_config(manifest):
    name = manifest['name']
    desc = ' '.join(manifest.get('description', '').split())
    return (
        '<?xml version="1.0"?>\n'
        f'<!-- {GENERATED_BANNER.format(name=name)} -->\n'
        '<model>\n'
        f'  <name>{name}</name>\n'
        '  <version>1.0</version>\n'
        f'  <sdf version="1.6">{name}.world</sdf>\n'
        f'  <description>{desc}</description>\n'
        '</model>\n'
    )


def generate(name):
    d = os.path.join(WORLDS, name)
    manifest_path = os.path.join(d, 'world.yaml')
    if not os.path.isfile(manifest_path):
        raise SystemExit(f'build_world: no manifest at {manifest_path}')

    with open(manifest_path) as f:
        manifest = yaml.safe_load(f)

    if manifest.get('name') != name:
        raise SystemExit(
            f'build_world: {manifest_path} declares name={manifest.get("name")!r} '
            f'but lives in worlds/{name}/. They must match — the directory name '
            f'is what `world:=` and model:// URIs resolve on.')

    world_path = os.path.join(d, f'{name}.world')
    with open(world_path, 'w') as f:
        f.write(build_world(manifest))
    with open(os.path.join(d, 'model.config'), 'w') as f:
        f.write(build_model_config(manifest))

    n_mesh = sum(1 for b in manifest['bodies'] if b['geometry']['type'] == 'mesh')
    print(f'{name}: {len(manifest["bodies"])} bodies ({n_mesh} mesh) -> {world_path}')


def discover():
    if not os.path.isdir(WORLDS):
        return []
    return sorted(n for n in os.listdir(WORLDS)
                  if os.path.isfile(os.path.join(WORLDS, n, 'world.yaml')))


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument('world', nargs='?', help='world name (directory under worlds/)')
    ap.add_argument('--all', action='store_true', help='regenerate every world')
    ap.add_argument('--list', action='store_true', help='list available worlds')
    args = ap.parse_args()

    worlds = discover()
    if args.list:
        print('\n'.join(worlds) if worlds else '(none)')
        return 0
    if args.all:
        for n in worlds:
            generate(n)
        return 0
    if not args.world:
        ap.error(f'name a world, or --all. Available: {", ".join(worlds) or "(none)"}')
    generate(args.world)
    return 0


if __name__ == '__main__':
    sys.exit(main())
