#!/usr/bin/env python3
"""Write a Nav2 map for a world that has no real room behind it.

    scripts/make_map.py small_office

`scripts/clone_world.py` goes the useful direction: a real room's occupancy map
becomes a world. This is the inverse, and it exists for exactly one case — a
world that was *designed* rather than cloned, like `small_office`. There is no
real room to record, so the manifest is the only thing that knows the geometry,
and without a map `nav:=true` has nothing to localise against.

Do NOT use this on a world that has a real counterpart. There the recorded map
is the reference and the model is what gets checked against it; generating the
map from the model instead would make `check_worlds.py`'s footprint test
tautological — the model would be compared with a picture of itself, and the
one check that can notice the model drifting away from the real room would
always pass.

The occupied cells come from the same rasteriser `check_worlds.py` uses, cut at
the burger's scan height, so the map and the drift check cannot disagree about
what the manifest says. Free space is flood-filled from the spawn pose, which
is what makes this a map rather than an outline: everything the robot could
reach is free, everything outside the walls stays unknown.
"""

import argparse
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(os.path.dirname(os.path.dirname(
    os.path.abspath(__file__))), 'tb3_bringup'))

import check_worlds                                   # noqa: E402
from tb3_bringup import worlds                        # noqa: E402

STEP = 0.05          # metres per cell; matches check_worlds' comparison grid
MARGIN = 4           # cells of unknown around the extent, so nothing clips
OCCUPIED, FREE, UNKNOWN = 0, 254, 205


def flood(occupied, start, lo, hi):
    """Cells reachable from `start` without crossing an occupied cell."""
    if start in occupied:
        raise SystemExit(
            'make_map: the spawn pose is inside a body; nothing to flood from')
    seen, stack = {start}, [start]
    while stack:
        cx, cy = stack.pop()
        for n in ((cx + 1, cy), (cx - 1, cy), (cx, cy + 1), (cx, cy - 1)):
            if n in seen or n in occupied:
                continue
            if not (lo[0] <= n[0] <= hi[0] and lo[1] <= n[1] <= hi[1]):
                # Escaped the extent: the room is not closed, and flooding on
                # would fill the whole plane. Say so rather than write a map
                # whose "free" space is the outdoors.
                raise SystemExit(
                    'make_map: free space escapes the world extent at '
                    f'{n} — the walls do not enclose the spawn pose')
            seen.add(n)
            stack.append(n)
    return seen


def build(name_or_path, out_name=None):
    world = worlds.World.load(name_or_path)
    occupied = check_worlds.rasterise(world)
    if occupied is None:
        raise SystemExit('make_map: this manifest cannot be rasterised '
                         '(a non-OBJ mesh, or roll/pitch on a body)')

    lo = (min(c[0] for c in occupied) - MARGIN, min(c[1] for c in occupied) - MARGIN)
    hi = (max(c[0] for c in occupied) + MARGIN, max(c[1] for c in occupied) + MARGIN)
    w, h = hi[0] - lo[0] + 1, hi[1] - lo[1] + 1

    sx, sy = world.spawn[0], world.spawn[1]
    free = flood(occupied, (int(sx // STEP), int(sy // STEP)), lo, hi)

    rows = bytearray()
    for r in range(h):
        # PGM row 0 is the TOP of the image, which is the HIGHEST y. Getting
        # this backwards produces a map that is mirrored about x and still
        # plans and drives without looking broken -- a bug this project has
        # already shipped once.
        cy = lo[1] + (h - 1 - r)
        for c in range(w):
            cell = (lo[0] + c, cy)
            rows.append(OCCUPIED if cell in occupied
                        else FREE if cell in free else UNKNOWN)

    name = out_name or world.name
    d = os.path.join(world.dir, 'map')
    os.makedirs(d, exist_ok=True)
    pgm = os.path.join(d, name + '.pgm')
    with open(pgm, 'wb') as f:
        f.write(b'P5\n')
        f.write(b'# generated by scripts/make_map.py from world.yaml -- '
                b'do not hand-edit\n')
        f.write(f'{w} {h}\n255\n'.encode())
        f.write(bytes(rows))

    yml = os.path.join(d, name + '.yaml')
    with open(yml, 'w') as f:
        f.write(
            '# Generated by scripts/make_map.py from world.yaml.\n'
            '# This world was designed, not cloned from a real room, so the\n'
            '# manifest is the only description of its geometry. See the\n'
            '# warning at the top of that script before copying this pattern.\n'
            f'image: {name}.pgm\n'
            f'resolution: {STEP}\n'
            f'origin: [{lo[0] * STEP:.3f}, {lo[1] * STEP:.3f}, 0.0]\n'
            'negate: 0\n'
            'occupied_thresh: 0.65\n'
            'free_thresh: 0.196\n')

    print(f'{world.name}: {w}x{h} cells at {STEP} m '
          f'({len(occupied)} occupied, {len(free)} free) -> {pgm}')
    if not world.manifest.get('map'):
        print(f'  add to {worlds.MANIFEST}:  map: map/{name}.yaml')
    return pgm


def main():
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument('world', help='registry name or path to a world directory')
    ap.add_argument('-o', '--name', help='output basename (default: the world name)')
    build(ap.parse_args().world, ap.parse_args().name)


if __name__ == '__main__':
    main()
